'use client';

import { useState } from 'react';
import { NAV_ICONS } from '@/components/layout/NavIcons';

type View = 'dashboard' | 'transactions' | 'cards' | 'forecast' | 'reports' | 'categories';
const nav: { id: View; label: string; icon: string }[] = [
  { id: 'dashboard', label: 'Visão geral', icon: '/dashboard' },
  { id: 'transactions', label: 'Transações', icon: '/transactions' },
  { id: 'cards', label: 'Cartões', icon: '/cards' },
  { id: 'forecast', label: 'Previsão', icon: '/forecast' },
  { id: 'reports', label: 'Relatórios', icon: '/reports' },
  { id: 'categories', label: 'Categorias', icon: '/categories' },
];
const money = (value: string) => <span className="num">{value}</span>;
const categories = [
  ['Moradia', 'R$ 2.140,00', 'mint'], ['Saúde', 'R$ 699,90', 'coral'], ['Transporte', 'R$ 500,43', 'amber'],
  ['Assinaturas', 'R$ 381,29', 'slate'], ['Compras', 'R$ 295,63', 'sky'],
];

function Stat({ label, value, detail, tone = 'default' }: { label: string; value: string; detail?: string; tone?: string }) {
  return <article className="stat"><p className="eyebrow">{label}</p><strong className={`value ${tone}`}>{money(value)}</strong>{detail && <p className="muted">{detail}</p>}</article>;
}
function MiniBars() { const bars = [[58,46],[92,66],[61,73],[57,54],[88,64],[51,25]]; return <div className="bars" aria-label="Fluxo mensal"><div className="axis"><span>R$ 12 mil</span><span>R$ 6 mil</span><span>R$ 0</span></div>{bars.map(([income, expense], i) => <div className="bar-group" key={i}><div className="bar income" style={{ height: `${income}%` }} /><div className="bar expense" style={{ height: `${expense}%` }} /><small>{['abr','mai','jun','jul','ago','set'][i]}</small></div>)}</div> }
function Progress({ value, tone = 'accent' }: { value: number; tone?: string }) { return <div className="progress"><span className={tone} style={{ width: `${value}%` }} /></div> }

function Dashboard() { return <>
  <div className="welcome"><div><p className="eyebrow">SETEMBRO DE 2026</p><h2>Bom dia, Gabriel</h2><p className="muted">Aqui está um resumo da sua vida financeira.</p></div><button className="primary">+ Novo lançamento</button></div>
  <section className="stats"><Stat label="Saldo em contas" value="R$ 28.979,82" detail="7 contas ativas" /><Stat label="Saldo do mês" value="R$ 2.948,67" detail="Receitas − despesas" tone="mint" /><Stat label="Receitas" value="R$ 5.109,28" tone="mint" /><Stat label="Despesas" value="R$ 2.160,61" tone="coral" /></section>
  <section className="goal-row"><article className="wide-card"><div className="card-head"><div><p className="eyebrow">META DE ECONOMIA</p><h3>Você está acima da meta</h3></div><span className="mint num">294,9%</span></div><Progress value={82} tone="mint" /><div className="card-foot"><span className="mint">Meta batida — R$ 1.948,67 acima</span><span className="muted num">R$ 2.948,67 / R$ 1.000,00</span></div></article><article className="wide-card"><div className="card-head"><div><p className="eyebrow">TETO DE GASTOS</p><h3>Ritmo saudável</h3></div><span className="num">54,0%</span></div><Progress value={54} /><div className="card-foot"><span className="muted">Restam R$ 1.839,39 para gastar</span><span className="muted num">R$ 2.160,61 / R$ 4.000,00</span></div></article></section>
  <section className="content-grid"><article className="panel chart-panel"><div className="card-head"><div><p className="eyebrow">FLUXO MENSAL</p><h3>Entradas e saídas</h3></div><button className="ghost">Últimos 6 meses⌄</button></div><MiniBars /></article><article className="panel"><div className="card-head"><div><p className="eyebrow">ORÇAMENTO POR CATEGORIA</p><h3>Onde seu dinheiro vai</h3></div><button className="ghost">Ver tudo →</button></div><div className="category-list">{categories.map(([name, amount, tone]) => <div className="category" key={name}><div><span className={`dot ${tone}`} /> <b>{name}</b></div><span className="muted num">{amount}</span><Progress value={name === 'Moradia' ? 76 : name === 'Saúde' ? 48 : 35} tone={tone} /></div>)}</div></article></section>
  <section className="content-grid bottom"><article className="panel"><div className="card-head"><div><p className="eyebrow">ATIVIDADE RECENTE</p><h3>Últimas transações</h3></div><button className="ghost">Ver todas →</button></div><TransactionRows /></article><article className="panel insight"><p className="eyebrow">INSIGHT DO MÊS</p><h3>Seu mês está equilibrado</h3><p className="muted">Você economizou <strong className="mint">R$ 2.948,67</strong> e gastou menos em compras do que no mês anterior.</p><button className="secondary">Ver relatório completo</button></article></section>
</> }
function TransactionRows() { return <div className="transactions">{[['Salário','Salário · Itaú','+ R$ 5.109,28','mint'],['Pneus','Transporte · Itaú','− R$ 470,53','coral'],['TotalPass','Saúde · Inter','− R$ 399,90','coral'],['Mercado Pago','Compras · Mercado Pago','− R$ 295,63','sky']].map(([name, sub, amount, tone]) => <div className="tx" key={name}><div className={`tx-icon ${tone}`}>{tone === 'mint' ? '↗' : '↘'}</div><div className="tx-copy"><b>{name}</b><span className="muted">{sub}</span></div><strong className={tone}>{money(amount)}</strong></div>)}</div> }
function Transactions() { return <><div className="welcome"><div><p className="eyebrow">SETEMBRO DE 2026</p><h2>Transações</h2><p className="muted">Lançamentos do mês selecionado</p></div><button className="primary">+ Novo lançamento</button></div><div className="filters"><input placeholder="Buscar descrição..." /><button className="select">Todas as categorias⌄</button><button className="select">Todas as contas⌄</button><button className="secondary">Exportar CSV</button></div><section className="panel"><TransactionRows /><TransactionRows /></section></> }
function Cards() { return <><div className="welcome"><div><p className="eyebrow">SETEMBRO DE 2026</p><h2>Cartões de crédito</h2><p className="muted">Acompanhe suas faturas sem surpresas.</p></div><button className="primary">+ Novo cartão</button></div><section className="stats"><Stat label="Faturas em aberto" value="R$ 2.013,33" tone="coral" /><Stat label="Total das faturas" value="R$ 2.013,33" detail="Compras do mês" /><Stat label="Limite disponível" value="R$ 16.916,67" detail="De R$ 18.930,00" tone="mint" /></section><div className="cards-grid">{[['Mercado Pago','R$ 468,60','sky'],['Itaú','R$ 763,54','amber'],['Inter','R$ 781,19','coral']].map(([name, amount, tone]) => <article className="credit-card" key={name}><div className="card-head"><h3><span className={`dot ${tone}`} /> {name}</h3><span className="muted">vence em 04/10</span></div><p className="eyebrow">FATURA DO MÊS</p><strong className="value coral">{money(amount)}</strong><Progress value={28} tone={tone} /><p className="muted">4 lançamentos · de R$ 3.000,00 do limite</p><TransactionRows /></article>)}</div></> }
function Generic({ view }: { view: View }) { const data: Record<View, [string,string]> = { forecast: ['Previsão','O que já está comprometido nos próximos meses'], reports: ['Relatórios','Comparativos e evolução do período'], categories: ['Categorias','Limites e consumo do mês'], dashboard:['',''],transactions:['',''],cards:['',''] }; return <><div className="welcome"><div><p className="eyebrow">SETEMBRO DE 2026</p><h2>{data[view][0]}</h2><p className="muted">{data[view][1]}</p></div><button className="primary">+ Adicionar</button></div><section className="stats"><Stat label="Total do período" value="R$ 33.375,73" tone="coral" /><Stat label="Receitas" value="R$ 43.369,20" tone="mint" /><Stat label="Resultado" value="R$ 9.993,47" tone="mint" /></section><section className="panel"><div className="card-head"><div><p className="eyebrow">VISÃO DETALHADA</p><h3>{view === 'forecast' ? 'Compromissos futuros' : view === 'reports' ? 'Evolução do patrimônio' : 'Categorias e limites'}</h3></div><button className="ghost">Este mês⌄</button></div><div className="placeholder-chart"><div className="line" /><div className="line line-2" /><div className="line line-3" /></div><TransactionRows /></section></> }

export default function FinancePreview() { const [view, setView] = useState<View>('dashboard'); const [collapsed, setCollapsed] = useState(false); return <div className={`preview ${collapsed ? 'collapsed' : ''}`}><aside className="sidebar"><div className="brand"><span>F</span><b>flowly</b></div><div className="profile"><div className="avatar">GO</div><div><b>Gabriel OG</b><small>Plano pessoal</small></div></div><p className="nav-label">MENU</p><nav>{nav.map(item => { const ItemIcon = NAV_ICONS[item.icon]; return <button className={view === item.id ? 'active' : ''} onClick={() => setView(item.id)} key={item.id}><ItemIcon /><span>{item.label}</span></button> })}</nav><div className="sidebar-bottom"><button onClick={() => setCollapsed(!collapsed)}><span className="collapse">{collapsed ? '→' : '←'}</span><span>Recolher menu</span></button><button><span className="gear">◌</span><span>Configurações</span></button></div></aside><main className="main"><header><button className="mobile-menu">☰</button><div><span className="crumb">Financeiro pessoal</span><span className="month">Setembro de 2026</span></div><div className="header-actions"><button className="icon-button">⌕</button><button className="icon-button">◐</button><button className="month-picker">‹ &nbsp; 09/26 &nbsp; ›</button><div className="mini-avatar">GO</div></div></header><div className="page">{view === 'dashboard' ? <Dashboard /> : view === 'transactions' ? <Transactions /> : view === 'cards' ? <Cards /> : <Generic view={view} />}</div></main></div> }

